name: Latest blog post workflow
on:
  schedule:
    # Runs on the 10th of each month
    - cron: "0 0 10 */1 *"
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://aristidebouix.cloud/en/index.xml"
