name: readme-scribe

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  readme-scribe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: muesli/readme-scribe@5a187a2a36ef894335f17a7d01c32b0e28c6d948
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      - name: replace placeholder for badge tag
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "badges_tag"
          replace: |
            <!--START_SECTION:badges-->
            <!--END_SECTION:badges-->
          include: README.md
      - name: replace placeholder for blogpost tag
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "blogpost_tag"
          replace: |
            <!-- BLOG-POST-LIST:START -->
            <!-- BLOG-POST-LIST:END -->
          include: README.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated README
          branch: main
          commit_user_name: readme-scribe 🤖
          commit_user_email: actions@github.com
          commit_author: readme-scribe 🤖 <actions@github.com>
